version: 0.0
os: linux
files:
  - source: /build/libs
    destination: /home/ec2-user/app/airbnb-clone-pg/jars
  - source: /scripts
    destination: /home/ec2-user/app/airbnb-clone-pg/jars

permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
