spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://airbnb-db:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none